/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    InputColor: typeof import('primevue/inputcolor')['default']
    InputColorArea: typeof import('primevue/inputcolorarea')['default']
    InputColorAreaBackground: typeof import('primevue/inputcolorareabackground')['default']
    InputColorAreaHandle: typeof import('primevue/inputcolorareahandle')['default']
    InputColorInput: typeof import('primevue/inputcolorinput')['default']
    InputColorSlider: typeof import('primevue/inputcolorslider')['default']
    InputColorSliderHandle: typeof import('primevue/inputcolorsliderhandle')['default']
    InputColorSliderTrack: typeof import('primevue/inputcolorslidertrack')['default']
    InputColorSwatch: typeof import('primevue/inputcolorswatch')['default']
    InputColorSwatchBackground: typeof import('primevue/inputcolorswatchbackground')['default']
    InputColorTransparencyGrid: typeof import('primevue/inputcolortransparencygrid')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Password: typeof import('primevue/password')['default']
    Popover: typeof import('primevue/popover')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Step: typeof import('primevue/step')['default']
    StepList: typeof import('primevue/steplist')['default']
    StepPanel: typeof import('primevue/steppanel')['default']
    StepPanels: typeof import('primevue/steppanels')['default']
    Stepper: typeof import('primevue/stepper')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
}
