const baseUrl = "http://192.168.0.3:5000/"; //ip de casa
//const baseUrl = "http://192.168.0.8:5000/"; //ip casa dona eke
const routeLogin = '/login';
const routeHome = '/home';
const routeWeeklyScore = '/weekly_score';
const routeUser = '/user';
const routeClub = '/club';
const routeClubDetails = '/club_details';
const routeClubWeeklyScore = '/club_weekly_score';
const routeOansist = '/oansist';
const routeLeadership = '/leadership';

const ursinho = "Ursinho";
const faisca = "Faísca";
const flama = "Flama";
const tocha = "Tocha";
const jv = "JV";
const vq7 = "VQ7";

const userSession = 'user_session';
const boxLeadership = 'leadership';
const boxClub = 'club';
const boxManual = 'manual';
const boxManualDivision = 'manual_division';
const boxOansist = 'oansist';
const boxMeeting = 'meeting';
const boxScore = 'score';
const boxScoreItem = 'score_item';
const boxRole = 'role';
const boxIdGenerator = 'id_generator';
